### ISSUE TITLE
No access to Heroku env

### ISSUE THREAD

**Issue by podviaznikov** [upworthy/heroku-buildpack-boot#1]
I defined some envs using `heroku config:set` syntax.
Now I'm trying to access those using `System/getenv` (https://github.com/hashobject/blog.hashobject.com/blob/master/build.boot#L27). But they `nil` for some reason.

Do you know why that is happening?

**Comment by paxan** [comment]
@podviaznikov thanks for reporting this issue.

I've added some logic that, similar to Clojure buildpack, allows extra variables to be exposed at build-time.

```
heroku config:set \
  BOOTBUILD_CONFIG_WHITELIST="AWS_ACCESS_KEY AWS_SECRET_KEY" \
  AWS_ACCESS_KEY=N0T50s3K3T \
  AWS_SECRET_KEY=S3CR3T
```

Please let me know if this addresses your concern.

**Comment by podviaznikov** [comment]
Thanks! trying right now and will report back

**Comment by podviaznikov** [comment]
Fix works. Thank you!

**Comment by paxan** [comment]
:+1:
