### ISSUE TITLE
add phantomjs to support prerendering of cljs

### ISSUE THREAD

**Issue by thedavidmeister** [upworthy/heroku-buildpack-boot#14]
Boot skips prerendering if phantomjs cannot be found.

It would be nice to be able to support this.

**Comment by paxan** [comment]
Google searching shows that there is at least one phantomjs buildpack. You can compose buildpacks, see `heroku buildpacks --help` and [the article about it from Heroku.](https://devcenter.heroku.com/articles/using-multiple-buildpacks-for-an-app)

Supporting extra tools like `phantomjs` during build time is out of scope for this buildpack.

**Comment by thedavidmeister** [comment]
@paxan thanks for the tip :) I'll try this out later.

**Comment by thedavidmeister** [comment]
adding a phantomjs buildpack did not seem to help unfortunately :(

```
-----> PhantomJS app detected
-----> Extracting PhantomJS 2.1.1 binaries to /tmp/build_6513c1c6e867bcf0b9e888a784864f8d/thedavidmeister-estimate-work-a8500151fc17f2c06cbb6ceb3e6c86bb5a9e44b9/vendor/phantomjs
-----> exporting PATH and LIBRARY_PATH
-----> Clojure (Boot) app detected
-----> Installing OpenJDK 1.8...done
-----> Using cached version of boot
-----> Copying boot... done
-----> Running: boot build -m
       Downloading https://github.com/boot-clj/boot/releases/download/2.5.5/boot.jar...
       Compiling 1/1 app.main...
       Compiling Hoplon pages...
       • index.cljs.hl
       Compiling ClojureScript...
       • index.html.js
       Skipping prerender: phantomjs not found on path.
```

I'm not sure if the problem is this buildpack or hoplon itself.

**Comment by paxan** [comment]
@thedavidmeister 
Looks like `phantomjs` is installed to `$HOME/vendor/phantomjs/bin` on a dyno.
But when downstream buildpack executes, `phantomjs` is not yet in PATH (it gets into PATH at run time, not build time).
Do you think there's a way to set an env var maybe with JAVA_OPTS or something that would help Hoplon locate this binary?

**Comment by paxan** [comment]
@thedavidmeister, I have [bad news:](https://github.com/hoplon/boot-hoplon/blob/1a114460b9d37146f0fe9621d8591f93695f1c15/src/hoplon/boot_hoplon/impl.clj#L11-L23) `boot-hoplon` currently assumes that `phantomjs` must be present in `PATH`. Maybe a better course of action is to submit a patch to `boot-hoplon` that allows location of PhantomJS to be customized via Java system properties, in addition to using env vars.

**Comment by thedavidmeister** [comment]
Thanks for figuring that out @paxan , I've opened up an issue against `boot-hoplon` linking back here.

**Comment by paxan** [comment]
You're welcome!
