### ISSUE TITLE
Quick question

### ISSUE THREAD

**Issue by podviaznikov** [upworthy/heroku-buildpack-boot#2]
After running `boot build` I cannot find `target` directory that I see locally. Instead I see all files put into `./app/.boot/cache/tmp/app/5/-ape7pg/`. Do you know why that is happening? Is there a way I can make either make buildpack write to `target` directory or maybe I can access real target diretory using some ENV?

**Comment by paxan** [comment]
If you run this from a dyno, do you get the same issue?

```
hk run bash
$ boot build
```

**Comment by podviaznikov** [comment]
Yes, I tried from bash and it's exactly the same. In fact that is how I was bale to get `./app/.boot/cache/tmp/app/5/-ape7pg/`.

**Comment by paxan** [comment]
``` sh
rm -rf ~/.boot
export BOOT_JVM_OPTIONS="$BOOT_JVM_OPTIONS -Duser.home=$HOME"
boot build
```

Try that ^^^ on a dyno. I am just wondering if perhaps the way compile runs boot has an effect on where the things go.

**Comment by podviaznikov** [comment]
Tried, it recreated `~/boot`. `~/target` is empty.

**Comment by paxan** [comment]
I'm running thin on the things to suggest :crying_cat_face: 

Have you tried to run this buildpack locally?

Before you begin, ensure `your-boot-project` has no `target` dir.

Basically, you'll need to clone the buildpack, say, to `~/a` and run:
`~/a/bin/compile your-boot-project ~/a/test-cache ~/a/test-env`

It will create `~/a/test-cache`, and `~/a/test-env` is optional.

**Comment by podviaznikov** [comment]
Tried locally. It didn't create target dir locally. I don't even know where did it write all the files.

**Comment by paxan** [comment]
How about in `~/a/test-cache`? Just curious. BTW, boot-clj copies files into separate dynamically created locations and resulting class path may look pretty surprising. It is because it tries to keep your project tree where you run it completely immutable. I am still learning all this all myself.

What happens if you run it w/o build pack?

First, install boot as prescribed by boot-clj docs.

``` sh
cd your-boot-project
git clean -dxf # careful!!! it will delete all non-tracked and ignored files
boot build
```

**Comment by podviaznikov** [comment]
Right now nothing is written to `my-repo/target` dir. Basically behavior is the same as with heroku.
But I'm 80% sure that before running `~/a/bin/compile your-boot-project ~/a/test-cache ~/a/test-env` it behaved differently (or at least several hours ago when I posted this ticket).
It seems that everything is written to `~/.boot` now.

**Comment by podviaznikov** [comment]
Ok, found the problem. It was with my last boot task in the chain. It returned `nil` and boot just didn't create target dir in that case. Thank you for the help!

**Comment by paxan** [comment]
No problem!
