### ISSUE TITLE
Using this buildpack i've got this error

### ISSUE THREAD

**Issue by benzen** [upworthy/heroku-buildpack-boot#3]
https://github.com/boot-clj/boot/issues/266
It seams to be related to miss fit between boot.sh and boot libs.
Is there something that can be done here?

**Comment by jkutner** [comment]
I think the solution to this is to purge the cache, which you can do by running:

```
$ heroku plugins:install https://github.com/heroku/heroku-repo.git
$ heroku repo:purge_cache -a <appname>
```

**Comment by paxan** [comment]
See: cff5ed9544986a25d1ee6ae9b8e4407c715f0b1d
@benzen does this help? I've ran into trouble when by boot executable was from one version but it was trying to bootstrap itself with newer version. Setting BOOT_VERSION to the version set by buildpack alleviated it.

**Comment by benzen** [comment]
I think so. Not quite sure, it's now fare fare way in my memory

2015-10-05 23:59 GMT-04:00 Pavel Repin notifications@github.com:

> See: cff5ed9
> https://github.com/upworthy/heroku-buildpack-boot/commit/cff5ed9544986a25d1ee6ae9b8e4407c715f0b1d
> @benzen https://github.com/benzen does this help? I've ran into trouble
> when by boot executable was from one version but it was trying to bootstrap
> itself with newer version. Setting BOOT_VERSION to the version set by
> buildpack alleviated it.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/upworthy/heroku-buildpack-boot/issues/3#issuecomment-145735774
> .

## 

Benjamin DREUX
