### ISSUE TITLE
bootstrapping error when specifying a BOOT_VERSION more recent than 2.4.0

### ISSUE THREAD

**Issue by dgellow** [upworthy/heroku-buildpack-boot#9]
Hey guys.
My builds fail when I'm setting BOOT_VERSION to a release number greater than 2.4.0.

I tried every releases since 2.2.0
- 2.2.0, 2.3.0 and 2.4.0 are ok
- from 2.4.1 to 2.5.5, they all failed

Any idea why ?
See my screenshots below.

<img width="712" alt="screen shot 2016-02-15 at 12 13 09" src="https://cloud.githubusercontent.com/assets/2451004/13040355/969ef56e-d3dd-11e5-93ec-df0481ed998e.png">

<img width="692" alt="screen shot 2016-02-15 at 12 13 29" src="https://cloud.githubusercontent.com/assets/2451004/13040357/9b7088fa-d3dd-11e5-82c7-d11c8c0b8d23.png">

**Comment by martinklepsch** [comment]
@dgellow The issue seems to be that newer versions check for `BOOT_AS_ROOT` which isn't set by default.

**Comment by martinklepsch** [comment]
Unfortunately `BOOT_AS_ROOT` cannot be set early enough as vars in  `BOOTBUILD_CONFIG_WHITELIST` are set after the first boot invocations. @paxan @jkutner If you guys want a PR for this I can provide one. Just wondering if we should set `BOOT_AS_ROOT` by default since in Docker things are "different"?

**Comment by jkutner** [comment]
It's really up to @paxan but i'd be happy to test a PR. thanks.

**Comment by jkutner** [comment]
@martinklepsch in the meantime, does `heroku config:set BOOT_AS_ROOT` work?

**Comment by martinklepsch** [comment]
@jkutner it doesn't. I think it is because the settings are only applied after bootstrap (which is when `boot` is first invoked).

**Comment by martinklepsch** [comment]
@jkutner opened #11 and #12 — if you're up for testing, that would be awesome! :)

**Comment by paxan** [comment]
@martinklepsch, will it help if...

```
if [[ -d "$env_dir" ]]; then
    # load the config vars allowed by BOOTBUILD_CONFIG_WHITELIST
    # (inspired by the way Clojure buildpack does it)
    if [[ -n "$BOOTBUILD_CONFIG_WHITELIST" ]]; then
        for key in $BOOTBUILD_CONFIG_WHITELIST; do
            if [[ -f "$env_dir/$key" ]]; then
                export "$key=$(cat "$env_dir/$key")"
            fi
        done
    fi
fi
```

... is moved to an earlier spot, next to other `export ...` statements?

**Comment by martinklepsch** [comment]
@paxan I think that would also address the problem yes. I will want to use this buildpack in a real project soon so happy to provide a PR if wanted.

**Comment by thedavidmeister** [comment]
hey, i tried the idea of moving the exports higher up in a fork.

didn't help.

I think it might have something to do with the 404 at:
https://github.com/boot-clj/boot/releases/download/2.4.1/boot.sh
https://github.com/boot-clj/boot/releases/download/2.5.0/boot.sh
etc...

**Comment by thedavidmeister** [comment]
@martinklepsch i think the approach in #11 seems right. I did something very similar in https://github.com/upworthy/heroku-buildpack-boot/pull/13
